language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
cache: pip

 
install: pip install -r requirements.txt
  
script:
  - python -m unittest
  

after_success: coverage report

notifications:
  email:
    recipients:
      - vaibhavsharma.ei@gmail.com
    on_success: always # default: change
    on_failure: always # default: always