language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python tests.py

notifications:
  email:
    recipients:
      - vaibhavsharma.ei@gmail.com
    on_success: always # default: change
    on_failure: always # default: always