language: python
python:
  - "2.7"
cache: pip

 
before_install: 
  - pip install winsound
  - cd Final_Capstone_Project/com/vaibhav/py
  
install:
  - pip install .
  - pip install -r requirements.txt
  
script:
  - python Alarm.py

notifications:
  email:
    recipients:
      - vaibhavsharma.ei@gmail.com
    on_success: always # default: change
    on_failure: always # default: always